###### Application Specific ######
dataset: 'CIFAR10' # options: CIFAR100, CIFAR10, ImageNet
network: 'DASNet34' # options: VGG166, DPN92, SENet18, densenet_cifar, GoogLeNet, ShuffleNetG2, ShuffleNetV2, ResNet34, ResNeXt29_2x64d, PreActResNet18, MobileNet, MobileNetV2, SqueezeNet, EfficientNetB0
optim_method: 'SGD' # options: SGD, AdaM, AdaGrad, RMSProp, AdaDelta
lr_scheduler: 'AdaS' # options: AdaS (with SGD), StepLR, CosineAnnealingWarmRestarts, OneCycleLR


###### Suggested Tune ######
n_trials: 1

beta: 0.7
beta_full: 0.95
full_train_only: False
init_lr: 0.1
init_conv_setting: '64,64,64,9'

adapt_trials: 25
epochs_per_trial: 20
mapping_condition_threshold: 10
delta_threshold_kernel: 0.03
delta_threshold: 0.02
delta_threshold_values:
  - 0.02
kernel_adapt: 1 #0 for NO kernel adaptations, 1 for kernel adaptions

min_scale_limit: 0.01
max_kernel_size: 9
min_kernel_size: 3
min_kernel_size_2: 1
max_conv_size: 256
min_conv_size: 32

stable_epoch: 0
factor_scale: 0.2
factor_scale_kernel: 1
blocks_per_superblock: -1

###### Suggested Default ######
max_epoch: 250
early_stop_threshold: -1 # set to -1 if you wish not to use early stop, or equally, set to a high value. Set to -1 if not using AdaS
early_stop_patience: 10 # epoch window to consider when deciding whether to stop
mini_batch_size: 128
min_lr: 0.00000000000000000001
zeta: 1.0
p: 1 # options: 1, 2.
loss: 'cross_entropy' # options: cross_entropy
